# Generated by Django 5.2.5 on 2025-08-28 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Loanease", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "contact",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", "Enter a valid 10 digit number."
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "loantype",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Loan"),
                            ("business", "Business Loan"),
                            ("student", "Student Loan"),
                            ("emergency", "Emergency Loan"),
                            ("mortgage", "Mortgage Loan"),
                            ("smbusiness", "Small Business Loan"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(max_length=500)),
            ],
        ),
    ]
